### ISSUE TITLE
Code Review from John Hicks

### ISSUE THREAD

**Issue by StoneYan1332** [vishalival/eep153-stanley-jevons#1]
Hi! First of all, your code is extremely impressive. I really appreciate the clarity provided by the explanations of what each code chunk does and the background information provided in the beginning. Your graphs are also clear, with the transparency on the bar graphs depicting the contrasts and similarities between Uganda and Tanzania. I don't have much advice to give regarding your code, nothing's erroring nor does it seem like there's any numerical issue. Maybe some helpful advice: make sure the units are matching on both sheets. Again, very impressive work!

**Comment by vishalival** [comment]
Hi, thanks for your kind feedback. We will definitely consider checking units on both sheets.

**Comment by vishalival** [comment]
Double-checked unit matching, issue closed
