### ISSUE TITLE
Terence Gorman Code Review

### ISSUE THREAD

**Issue by kimberleyfan** [vishalival/eep153-stanley-jevons#2]
Awesome job!! Love the commented code descriptions and easy to follow code structure. Overall, very clean, fast code and great findings. 

If I were to suggest one small thing - for the nutritional content section, there could be more clarity perhaps. In all the other sections, there's a Tanzania and an Uganda section shown, so I was a little confused when I only saw the code for Tanzania in this section (I took a second look and then understood that Uganda's dataset already had a FCT given). Maybe you can list the first few rows of the Uganda's dataset to keep the pattern consistent? And also perhaps making it more clear what your sources were and if it's US government recommendations or the countries own recommendations. 

Looking forward to seeing how the findings can be connected to facts and history about the two countries in the final presentation! 

Good luck!

**Comment by vishalival** [comment]
Thank you, this feedback is really valuable for our final project, we definitely need to boost clarity on some aspects of the work. We have implemented some of these changes too.
